// Regenerate migrations/cards-seed.sql from all TS decks.
//
// Workflow:
//   1. Import every Card[] export from src/data/*.ts (wired below — see DECKS).
//   2. Merge into an id-keyed map (last write wins; earlier decks lose on collision).
//   3. Emit a single SQL file with:
//        DELETE FROM cards;
//        INSERT INTO cards (...) VALUES (...), (...), ...;
//      using INSERT OR REPLACE semantics via the DELETE+INSERT pair.
//   4. `wrangler d1 execute ... --file=migrations/cards-seed.sql --remote` applies it.
//
// Keep DECKS in sync with src/lib/storage.ts — the two files must reference the
// same set of exported arrays, otherwise the browser and D1 diverge.

import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

import { CARDS } from "../src/data/cards";
import { FRENCH_A1_CARDS } from "../src/data/french-a1";
import { QUANT_CARDS } from "../src/data/quant-cards";
import { QUANT_MATH_CARDS } from "../src/data/quant-math-cards";
import { QUANT_INTERACTIVE_CARDS } from "../src/data/quant-interactive-cards";
import { CONJUGATION_CARDS } from "../src/data/conjugation-cards";
import { BUSINESS_CARDS } from "../src/data/business-cards";
import { MODULE_DESIGN_CARDS } from "../src/data/module-design-cards";
import { KAHNEMAN_CARDS } from "../src/data/kahneman-cards";
import { DDIA_GLOSSARY_CARDS } from "../src/data/ddia-glossary-cards";
import { FINETUNING_CARDS } from "../src/data/finetuning-cards";
import { POLYMARKET_DISCIPLINE_CARDS } from "../src/data/polymarket-discipline-cards";
import { AUSTRIAN_DEFLATIONISM_CARDS } from "../src/data/austrian-deflationism-cards";

import type { Card } from "../src/types";

const DECKS: { name: string; cards: Card[] }[] = [
  { name: "CARDS", cards: CARDS },
  { name: "FRENCH_A1_CARDS", cards: FRENCH_A1_CARDS },
  { name: "QUANT_CARDS", cards: QUANT_CARDS },
  { name: "QUANT_MATH_CARDS", cards: QUANT_MATH_CARDS },
  { name: "QUANT_INTERACTIVE_CARDS", cards: QUANT_INTERACTIVE_CARDS },
  { name: "CONJUGATION_CARDS", cards: CONJUGATION_CARDS },
  { name: "BUSINESS_CARDS", cards: BUSINESS_CARDS },
  { name: "MODULE_DESIGN_CARDS", cards: MODULE_DESIGN_CARDS },
  { name: "KAHNEMAN_CARDS", cards: KAHNEMAN_CARDS },
  { name: "DDIA_GLOSSARY_CARDS", cards: DDIA_GLOSSARY_CARDS },
  { name: "FINETUNING_CARDS", cards: FINETUNING_CARDS },
  { name: "POLYMARKET_DISCIPLINE_CARDS", cards: POLYMARKET_DISCIPLINE_CARDS },
  { name: "AUSTRIAN_DEFLATIONISM_CARDS", cards: AUSTRIAN_DEFLATIONISM_CARDS },
];

// SQLite single-quote escape.
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

function rowFor(c: Card): string {
  const category = q(c.category ?? "");
  const front = q(c.front ?? "");
  const back = q(c.back ?? "");
  const keyPoints = q(JSON.stringify(c.keyPoints ?? []));
  const data = q(JSON.stringify(c));
  return `(${c.id}, ${category}, ${front}, ${back}, ${keyPoints}, ${data})`;
}

function main() {
  const merged = new Map<number, { deck: string; card: Card }>();
  const collisions: string[] = [];

  for (const { name, cards } of DECKS) {
    for (const card of cards) {
      if (merged.has(card.id)) {
        const prev = merged.get(card.id)!;
        collisions.push(
          `  id=${card.id}: ${prev.deck} vs ${name} (later wins)`
        );
      }
      merged.set(card.id, { deck: name, card });
    }
  }

  if (collisions.length) {
    console.warn(`[sync-decks] ${collisions.length} ID collision(s):`);
    for (const c of collisions) console.warn(c);
  }

  const rows = [...merged.values()]
    .sort((a, b) => a.card.id - b.card.id)
    .map((x) => rowFor(x.card));

  // SQLite has a default SQLITE_MAX_LENGTH (~1MB) per statement. A single
  // INSERT with 600+ cards exceeds this. Chunk into smaller INSERTs.
  const CHUNK = 50;
  const chunks: string[][] = [];
  for (let i = 0; i < rows.length; i += CHUNK) {
    chunks.push(rows.slice(i, i + CHUNK));
  }

  const header = [
    "-- Generated by scripts/sync-decks-to-d1.ts — DO NOT EDIT BY HAND.",
    `-- ${new Date().toISOString()} — ${rows.length} cards from ${DECKS.length} decks, ${chunks.length} chunks.`,
    "-- Apply with: wrangler d1 execute flashcards-db --remote --file=migrations/cards-seed.sql",
    "",
    "DELETE FROM cards;",
    "",
  ].join("\n");

  const body = chunks
    .map(
      (chunk) =>
        `INSERT INTO cards (id, category, front, back, key_points, data) VALUES\n${chunk.join(",\n")};`
    )
    .join("\n\n");

  const sql = `${header}\n${body}\n`;

  const here = dirname(fileURLToPath(import.meta.url));
  const out = resolve(here, "..", "migrations", "cards-seed.sql");
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, sql);

  console.log(
    `[sync-decks] wrote ${rows.length} cards → migrations/cards-seed.sql`
  );
  console.log(
    "[sync-decks] next: npm run sync-decks:apply:remote  (or :local to test)"
  );
}

main();
