import type { Lesson, Section } from "../types";

// === NVIDIA Senior Deep Learning Compiler Engineer — Learning Path ===
//
// Source: https://www.linkedin.com/jobs/view/4395484250/
// Generated by the /job-to-path skill, 2026-04-18.
// Full vault map: learning/Career/nvidia-dl-compiler-learning-path.md
//
// Lesson IDs use the "dlc-" prefix. Card IDs reserved 9000-9099.
// Cards are intentionally empty arrays — cards are written by a separate
// /build pass. This file only ships the curriculum scaffold.
//
// === RED TEAM VERDICT: PARTIAL — DO NOT WIRE THE FULL SECTION ===
//
// Only ~5 of 21 lessons are flashcard-appropriate. The rest require
// implementation work (writing passes, kernels, ops) that flashcards
// cannot substitute for. See the markdown vault map for full rulings.
//
// If wiring into the app, use DL_COMPILER_SUBSET below instead of
// DL_COMPILER_SECTION. The subset covers "compiler literacy for an ML
// practitioner" — useful regardless of the NVIDIA-specific career pivot.
//
// The full 21-lesson DL_COMPILER_SECTION is kept for reference but
// NOT recommended for wiring. Build a GitHub PR portfolio first.

export const DL_COMPILER_SECTION: Section = {
  id: "dl-compiler",
  title: "Deep Learning Compiler Engineering",
  description:
    "Compiler internals, PyTorch/JAX framework internals, CUDA and ML compiler ecosystem — scaffolded from the NVIDIA Thunder job posting. Treat as terminology + concept map; implementation practice is a separate track.",
  icon: "&#9881;",
  color: "#76b900",
  lessons: [
    // ----- Domain 1: Compiler Fundamentals -----
    {
      id: "dlc-lexing-parsing",
      sectionId: "dl-compiler",
      title: "Lexing, parsing, and ASTs",
      description:
        "Source text → tokens → parse tree → AST. Why abstract syntax is a different beast from concrete syntax.",
      cards: [],
      prerequisites: [],
      concepts: [
        "Tokens are regex-class lexemes; grammars are context-free rules over them",
        "Recursive descent parses by following the grammar; parser generators (yacc, ANTLR) automate it",
        "AST nodes drop punctuation and structure that the grammar needed but the semantics don't",
        "Concrete syntax tree preserves source for tooling; AST is what the compiler actually uses",
      ],
    },
    {
      id: "dlc-ir-and-ssa",
      sectionId: "dl-compiler",
      title: "Intermediate representations and SSA form",
      description:
        "Why every real compiler has an IR, and why SSA (single static assignment) is the dominant shape.",
      cards: [],
      prerequisites: ["dlc-lexing-parsing"],
      concepts: [
        "An IR decouples the frontend (parsing) from the backend (codegen)",
        "Three-address code is a common shape: each instruction defines one value",
        "SSA form assigns each variable exactly once; phi nodes merge values at control-flow joins",
        "Dominator trees define where phi nodes go and which definitions reach a use",
        "LLVM IR, MLIR, and most modern compilers use SSA; the dataflow properties are easier to reason about",
      ],
    },
    {
      id: "dlc-dataflow-analysis",
      sectionId: "dl-compiler",
      title: "Dataflow and control-flow analysis",
      description:
        "Reaching definitions, live variables, and the fixpoint iteration that powers optimization.",
      cards: [],
      prerequisites: ["dlc-ir-and-ssa"],
      concepts: [
        "Control-flow graphs (CFG) model branching; nodes are basic blocks, edges are transfers",
        "Dataflow analyses compute properties per program point via fixpoint iteration",
        "Reaching definitions answers 'which assignment sets this variable at point p?'",
        "Live-variable analysis answers 'will this value be used before being overwritten?'",
        "SSA simplifies most dataflow analyses because each value has a single definition",
      ],
    },
    {
      id: "dlc-optimization-passes",
      sectionId: "dl-compiler",
      title: "Optimization passes",
      description:
        "Dead code elimination, constant propagation, CSE, LICM, peephole. The bread and butter of compiler work.",
      cards: [],
      prerequisites: ["dlc-dataflow-analysis"],
      concepts: [
        "Dead code elimination removes computations whose results are never used",
        "Constant propagation replaces known-constant values; constant folding evaluates them",
        "Common subexpression elimination caches a computed value instead of recomputing",
        "Loop-invariant code motion hoists computations that don't depend on the loop body",
        "Peephole optimizations rewrite small local patterns (x*1 → x, x+0 → x)",
        "Pass ordering matters and is an open research problem",
      ],
    },
    {
      id: "dlc-codegen-regalloc",
      sectionId: "dl-compiler",
      title: "Code generation and register allocation",
      description:
        "From IR to machine code: instruction selection, register allocation, scheduling.",
      cards: [],
      prerequisites: ["dlc-optimization-passes"],
      concepts: [
        "Instruction selection maps IR ops to target instructions via pattern matching or DAG coverage",
        "Register allocation is NP-hard; graph coloring and linear scan are the two dominant approaches",
        "Spilling is the fallback when a variable can't stay in a register; it hits memory",
        "Instruction scheduling reorders operations to maximize pipeline utilization",
        "Calling conventions define which registers hold arguments / returns / caller-saved vs callee-saved",
      ],
    },

    // ----- Domain 2: PyTorch Internals -----
    {
      id: "dlc-pytorch-eager",
      sectionId: "dl-compiler",
      title: "PyTorch eager mode and autograd",
      description:
        "How PyTorch runs Python today: the dispatcher, autograd tape, and why graph compilation is hard on top.",
      cards: [],
      prerequisites: ["dlc-ir-and-ssa"],
      concepts: [
        "Tensor holds metadata + a pointer to Storage; Storage holds raw memory",
        "The dispatcher routes ops across keys: CPU/CUDA/autograd/functionalize",
        "Autograd records a tape of differentiable ops; backward() walks it in reverse",
        "Eager mode executes one op at a time — no graph visibility — so compilation requires capturing a trace",
      ],
    },
    {
      id: "dlc-fx-graph",
      sectionId: "dl-compiler",
      title: "torch.fx and symbolic tracing",
      description:
        "PyTorch's first-class graph IR; symbolic vs concrete tracing; why tracers break on control flow.",
      cards: [],
      prerequisites: ["dlc-pytorch-eager"],
      concepts: [
        "torch.fx gives PyTorch a proper Graph / Node / GraphModule IR",
        "Symbolic tracing records operations on Proxy tensors without running them",
        "Concrete tracing records operations on real tensors; faster but loses dynamism",
        "Tracers cannot see Python-level control flow that depends on tensor values (if x.sum() > 0:)",
        "FX graphs are the substrate for quantization, partitioning, and backend export",
      ],
    },
    {
      id: "dlc-torchdynamo",
      sectionId: "dl-compiler",
      title: "TorchDynamo",
      description:
        "Bytecode-level capture of PyTorch programs. How torch.compile sees graph boundaries.",
      cards: [],
      prerequisites: ["dlc-fx-graph"],
      concepts: [
        "Dynamo rewrites Python bytecode at frame-evaluation time using PEP 523",
        "It emits an FX graph plus guards — conditions that must hold for the compiled code to be valid",
        "Graph breaks happen when Dynamo can't capture a Python operation; execution falls back to eager",
        "Guards include tensor shapes, dtypes, Python object identities",
        "Dynamo is strictly more powerful than FX symbolic trace because it sees control flow",
      ],
    },
    {
      id: "dlc-torchinductor",
      sectionId: "dl-compiler",
      title: "TorchInductor",
      description:
        "PyTorch's default compiler backend. Scheduling IR, Triton codegen, kernel fusion on GPU.",
      cards: [],
      prerequisites: ["dlc-torchdynamo", "dlc-codegen-regalloc"],
      concepts: [
        "Inductor consumes FX graphs from Dynamo and produces fused GPU kernels",
        "It has a define-by-run scheduling IR with symbolic shapes",
        "CUDA codegen goes through Triton; CPU codegen goes through C++/OpenMP",
        "Fusion is the primary source of speedup — elementwise chains, reduction fusion, view folding",
        "Performance characteristics depend heavily on shape specialization; recompilation cost is real",
      ],
    },

    // ----- Domain 3: CUDA and GPU Programming -----
    {
      id: "dlc-gpu-execution-model",
      sectionId: "dl-compiler",
      title: "GPU execution model",
      description:
        "SM, warp, thread block, SIMT — the hardware the compiler targets.",
      cards: [],
      prerequisites: [],
      concepts: [
        "A Streaming Multiprocessor (SM) executes warps of 32 threads in SIMT fashion",
        "Thread blocks are scheduled onto SMs; threads within a block share memory and can sync",
        "Memory hierarchy: registers (per-thread) → shared (per-block) → L1/L2 → HBM (global)",
        "Occupancy is the ratio of active warps to maximum warps an SM can support",
        "Warp divergence (threads in a warp taking different branches) serializes execution and hurts perf",
      ],
    },
    {
      id: "dlc-cuda-kernels",
      sectionId: "dl-compiler",
      title: "CUDA kernel writing and memory coalescing",
      description:
        "Writing fast GPU kernels: coalesced access, shared-memory tiling, bank conflicts.",
      cards: [],
      prerequisites: ["dlc-gpu-execution-model"],
      concepts: [
        "Coalesced access: adjacent threads read adjacent memory addresses, one transaction instead of many",
        "Shared memory tiling: load a block of global memory into shared once, reuse many times",
        "Bank conflicts: shared memory is banked 32-way; strided access patterns serialize",
        "Cooperative groups give structured synchronization beyond __syncthreads()",
        "Warp-level primitives (shfl, ballot, vote) enable fine-grained reductions without shared memory",
      ],
    },
    {
      id: "dlc-gpu-profiling",
      sectionId: "dl-compiler",
      title: "GPU performance profiling",
      description:
        "Nsight Systems, Nsight Compute, and the roofline model. Where time actually goes.",
      cards: [],
      prerequisites: ["dlc-gpu-execution-model"],
      concepts: [
        "Nsight Systems: timeline profiler — good for finding idle periods and kernel launch overhead",
        "Nsight Compute: per-kernel deep dive — warp stalls, memory throughput, instruction mix",
        "The roofline model plots achieved FLOPS vs arithmetic intensity against hardware bounds",
        "Memory-bound kernels hit the bandwidth ceiling; compute-bound kernels hit peak FLOPS",
        "Most ML workloads are memory-bound; fusion reduces memory traffic",
      ],
    },
    {
      id: "dlc-triton",
      sectionId: "dl-compiler",
      title: "Triton as a GPU DSL",
      description:
        "Block-level kernel programming that sits between CUDA and PyTorch. Inductor's codegen target.",
      cards: [],
      prerequisites: ["dlc-cuda-kernels"],
      concepts: [
        "Triton is a Python-embedded DSL that compiles to PTX via LLVM",
        "Programs are written per block of threads, not per thread — the compiler handles SIMT mapping",
        "Automatic optimization: shared memory allocation, coalescing, pipeline",
        "Autotuning searches over tile sizes and num_warps",
        "Triton kernels often match hand-tuned CUDA within 10% at a fraction of the code",
      ],
    },

    // ----- Domain 4: ML Compiler Ecosystem -----
    {
      id: "dlc-mlir",
      sectionId: "dl-compiler",
      title: "MLIR",
      description:
        "LLVM's multi-level IR framework. Dialects, progressive lowering, pattern rewriting.",
      cards: [],
      prerequisites: ["dlc-ir-and-ssa"],
      concepts: [
        "MLIR is extensible: you define dialects (vocabularies of ops) for your domain",
        "Progressive lowering: high-level ops → mid-level → low-level LLVM IR through passes",
        "TableGen drives op definitions declaratively; generates boilerplate",
        "Pattern rewrites transform IR via declarative DAG-to-DAG match-and-replace",
        "MLIR underpins IREE, Flang, CIRCT, and increasingly TPU/accelerator toolchains",
      ],
    },
    {
      id: "dlc-tvm",
      sectionId: "dl-compiler",
      title: "TVM and Relay",
      description:
        "Apache TVM's end-to-end deep learning compiler stack: Relay IR, tensor expressions, auto-scheduling.",
      cards: [],
      prerequisites: ["dlc-ir-and-ssa"],
      concepts: [
        "Relay is TVM's high-level graph IR — functional, typed, with support for control flow",
        "Tensor Expression language describes compute + schedule separately",
        "Ansor auto-scheduler searches the schedule space with learned cost models",
        "Multi-target: CPU, CUDA, Vulkan, WebAssembly, custom accelerators",
        "Compared to Inductor: TVM targets diverse hardware; Inductor targets PyTorch-on-NVIDIA-hard",
      ],
    },
    {
      id: "dlc-xla-iree",
      sectionId: "dl-compiler",
      title: "XLA and IREE",
      description:
        "Google's HLO IR and the MLIR-based runtime IREE. What PyTorch isn't.",
      cards: [],
      prerequisites: ["dlc-mlir"],
      concepts: [
        "XLA's HLO IR is JAX's and TF's primary compilation target; a stable ML-compute vocabulary",
        "Op fusion in XLA is conservative but predictable; kernels are generated ahead-of-time",
        "IREE takes MLIR all the way to VM bytecode; flow/stream/hal dialects separate concerns",
        "IREE targets mobile + server + accelerators through a single toolchain",
        "The XLA ↔ Inductor comparison illustrates AOT-compilation vs JIT-specialization tradeoffs",
      ],
    },

    // ----- Domain 5: JAX and Functional Transformations -----
    {
      id: "dlc-jax-transforms",
      sectionId: "dl-compiler",
      title: "JAX core transformations",
      description:
        "jit, grad, vmap, pmap — JAX's composable function transformations.",
      cards: [],
      prerequisites: ["dlc-pytorch-eager"],
      concepts: [
        "JAX functions must be pure (no side effects, no in-place mutation)",
        "jit traces a Python function to a jaxpr and compiles it via XLA",
        "grad computes derivatives via automatic differentiation on the jaxpr",
        "vmap vectorizes a function over a new axis without manual batching",
        "pmap shards computation across devices; a restricted form of spmd parallelism",
      ],
    },
    {
      id: "dlc-jax-pipeline",
      sectionId: "dl-compiler",
      title: "JAX compilation pipeline",
      description:
        "From Python function to XLA HLO to hardware. Where sharding and Pallas fit.",
      cards: [],
      prerequisites: ["dlc-jax-transforms", "dlc-xla-iree"],
      concepts: [
        "jaxpr is JAX's functional IR — pure, typed, composable with transformations",
        "jaxpr → HLO → XLA compilation → device code",
        "pjit + sharding annotations describe how tensors partition across devices",
        "Pallas is a JAX-integrated Triton-like for writing custom kernels",
        "Compared to PyTorch 2.0: JAX had graph-first compilation from day one, making the story simpler",
      ],
    },

    // ----- Domain 6: Performance Engineering -----
    {
      id: "dlc-fusion-strategies",
      sectionId: "dl-compiler",
      title: "Kernel fusion strategies",
      description:
        "Vertical, horizontal, reduction fusion. Where the speedups actually come from.",
      cards: [],
      prerequisites: ["dlc-torchinductor", "dlc-cuda-kernels"],
      concepts: [
        "Vertical fusion merges producer + consumer ops so intermediate values stay in registers",
        "Horizontal fusion batches independent ops that share inputs",
        "Reduction fusion combines a compute chain with its reduction in one kernel",
        "Fusion decisions balance register pressure vs memory traffic",
        "ML workloads are usually memory-bound; fused kernels improve arithmetic intensity",
      ],
    },
    {
      id: "dlc-profiling-workflows",
      sectionId: "dl-compiler",
      title: "Profiling ML workloads end-to-end",
      description:
        "PyTorch Profiler, Nsight, CUDA Graphs, bubble analysis. The workflow a compiler engineer runs daily.",
      cards: [],
      prerequisites: ["dlc-gpu-profiling"],
      concepts: [
        "PyTorch Profiler gives a Python-level view: time per op, CUDA stream timeline",
        "Nsight Systems drills into the CUDA timeline; find idle bubbles, launch overhead",
        "CUDA Graphs batch kernel launches, eliminating per-launch overhead",
        "Bubble analysis identifies periods where the GPU is idle waiting for the host",
        "Regressions are caught by comparing timeline snapshots across commits",
      ],
    },
    {
      id: "dlc-compiler-correctness",
      sectionId: "dl-compiler",
      title: "Compiler correctness and regression testing",
      description:
        "Numerical tolerance, fuzz testing, min-repro extraction — how you keep a compiler honest.",
      cards: [],
      prerequisites: ["dlc-optimization-passes"],
      concepts: [
        "Reference implementations (eager PyTorch) are the ground truth for compiled output",
        "Numerical tolerance must account for fp associativity: reordered reductions differ in the last bits",
        "Fuzz testing synthesizes random graphs and checks compiler doesn't crash / miscompile",
        "Min-reproducer extraction: given a failing model, bisect the graph to find the smallest repro",
        "CI must run across hardware classes (A100, H100, consumer) — bugs hide in shape/dtype corners",
      ],
    },
  ] satisfies Lesson[],
};

// Convenience: the full list of lesson IDs for ordering / progression UI.
export const DL_COMPILER_LESSON_ORDER: string[] = DL_COMPILER_SECTION.lessons.map(
  (l) => l.id
);

// === Recommended subset — "compiler literacy for an ML practitioner" ===
//
// This is what the red team said to actually ship. Useful for quant/ML
// work whether or not you pursue the NVIDIA role. Drops Domain 1
// (fundamentals — needs implementation) and Domain 4 (ecosystem survey —
// needs 6mo per framework, not 3 lessons). Scopes Domain 2 to the user's
// perspective, not the implementer's.

const SUBSET_LESSON_IDS: ReadonlySet<string> = new Set([
  // Domain 3: CUDA & GPU — full
  "dlc-gpu-execution-model",
  "dlc-cuda-kernels",
  "dlc-gpu-profiling",
  "dlc-triton",
  // Domain 2: PyTorch internals — user-level only (compile pipeline)
  "dlc-torchdynamo",
  "dlc-torchinductor",
  // Domain 5: JAX core transforms (concept literacy)
  "dlc-jax-transforms",
  // Domain 6: Performance Engineering — full
  "dlc-fusion-strategies",
  "dlc-profiling-workflows",
  "dlc-compiler-correctness",
]);

export const DL_COMPILER_SUBSET: Section = {
  id: "dl-compiler-literacy",
  title: "Compiler Literacy for ML Practitioners",
  description:
    "Subset of the full DL-compiler path — useful whether or not you pivot careers. CUDA, Triton, torch.compile internals, JAX transforms, profiling, fusion. Drops the write-a-compiler fundamentals and the ecosystem survey in favor of the lessons that help you use modern ML compilers well.",
  icon: "&#9881;",
  color: "#76b900",
  lessons: DL_COMPILER_SECTION.lessons.filter((l) => SUBSET_LESSON_IDS.has(l.id)),
};
