import type { Section } from "../types";

// === Tailcall Founding/Staff Backend Engineer — Learning Path ===
//
// Source: https://docs.google.com/forms/d/e/1FAIpQLSelWLZjeO-DnovclHTeq1GEqYcWGQGo1WGOnlwaclNdyGvljQ/viewform
// Generated by the /job-to-path skill, 2026-04-19.
// Full vault map: learning/Career/tailcall-founding-backend-learning-path.md
//
// Lesson IDs use the "tbe-" prefix. Card IDs reserved 9100-9199.
// Cards are intentionally empty arrays — cards are written by a separate
// /build pass. This file only ships the curriculum scaffold.
//
// === RED TEAM VERDICT: PARTIAL — USE AT ~30% WEIGHT ===
//
// The 5-10yr experience filter dominates; a flashcard path cannot close it.
// The real hiring signal for a founding engineer at an AI dev-tooling startup
// is an OSS project at the Rust + LLM-tooling intersection, not Anki recall.
//
// Run this curriculum for terminology retention + interview prep only.
// Put 70% of effort into shipping public code Tailcall would want to read.

export const FOUNDING_BACKEND_SECTION: Section = {
  id: "founding-backend",
  title: "Founding/Staff Backend Engineer",
  description:
    "Rust backend stack, cloud-native distribution, and staff-engineer practice — scaffolded from the Tailcall founding-engineer posting. Focuses on the 4 genuine gaps (Rust backend, K8s, Terraform, staff-scope) plus 2 standout-signal lessons on AI backend. Flashcards are scaffold for vocabulary retention; real progress is measured in shipped OSS.",
  icon: "&#9881;",
  color: "#ce422b",
  lessons: [
    // ----- Domain 1: Rust Backend Stack -----
    {
      id: "tbe-rust-async-runtime",
      sectionId: "founding-backend",
      title: "The tokio runtime and Rust async model",
      description:
        "The jump from systems Rust to backend Rust is async. Understand the runtime, task scheduling, and when each spawn primitive applies.",
      cards: [],
      prerequisites: [],
      concepts: [
        "async fn returns a Future; nothing executes until polled by a runtime",
        "tokio::spawn for concurrent I/O-bound tasks; spawn_blocking for CPU-bound or sync-only work",
        "select! races futures; join! awaits all; try_join! short-circuits on error",
        "Send + 'static is the bound most spawn patterns require — learn why",
        "Work-stealing scheduler moves tasks between threads; hot locks hurt more than in single-threaded async",
      ],
    },
    {
      id: "tbe-axum-handlers-and-state",
      sectionId: "founding-backend",
      title: "Axum handlers, extractors, and shared state",
      description:
        "Axum is the Tokio team's web framework and the default 2026 Rust backend choice. Core mental model: extractors compose, Tower middleware is where real work happens.",
      cards: [],
      prerequisites: ["tbe-rust-async-runtime"],
      concepts: [
        "Handler = async fn with 0-N extractor parameters returning IntoResponse",
        "State<T> is the canonical shared-state extractor; pass PgPool, config, clients via State",
        "Extractors run in order and consume the request body once — ordering matters",
        "IntoResponse lets errors-as-types propagate without unwrap",
        "Tower middleware (trace, cors, rate-limit, auth) composes via .layer() — the real composition primitive",
      ],
    },
    {
      id: "tbe-sqlx-compile-time-sql",
      sectionId: "founding-backend",
      title: "SQLx compile-time-verified SQL",
      description:
        "SQLx's macros verify SQL against a real database at compile time. This is the defining feature of Rust backend development and the closest thing Rust has to an ORM without being one.",
      cards: [],
      prerequisites: ["tbe-rust-async-runtime"],
      concepts: [
        "query! and query_as! macros hit a live database during cargo check — cache via cargo sqlx prepare for CI",
        "Compile-time verification catches schema drift before deploy",
        "PgPool is a connection pool; size it to (CPU cores × 2) as a starting point, tune from there",
        "Transactions via .begin() returning a Transaction that must be explicitly committed",
        "sqlx-cli handles migrations; commit migration files with your schema changes",
      ],
    },
    {
      id: "tbe-rust-deployment",
      sectionId: "founding-backend",
      title: "Rust backend deployment patterns",
      description:
        "Multi-stage Docker builds, structured logging, and the boring production discipline that ships Rust services.",
      cards: [],
      prerequisites: ["tbe-axum-handlers-and-state"],
      concepts: [
        "Multi-stage Dockerfile: rust:1.XX-slim for build, debian:bookworm-slim or distroless for runtime",
        "Binary is large but self-contained — cold start is fast, image size is the concern",
        "tracing + tracing_subscriber with JSON output for log-aggregator compatibility",
        "Graceful shutdown via tokio::signal::ctrl_c + server.with_graceful_shutdown()",
        "Health endpoints split liveness (process up) from readiness (dependencies reachable)",
      ],
    },

    // ----- Domain 2: Distributed Systems Applied -----
    {
      id: "tbe-event-driven-patterns",
      sectionId: "founding-backend",
      title: "Event-driven patterns in production",
      description:
        "When event sourcing earns its complexity vs CRUD; the outbox pattern for transactional publication; idempotency discipline across services.",
      cards: [],
      prerequisites: [],
      concepts: [
        "Event sourcing trades query simplicity for auditability and replayability — default no, yes when legal/regulatory says so",
        "Outbox pattern writes events to the same DB transaction as the state change, then ships to broker — solves dual-write",
        "Idempotency keys on mutating endpoints make retries safe across network partitions",
        "CQRS splits read and write models; use it when read scale diverges from write scale, not because it's trendy",
        "Dead-letter queues + replay tooling are the unglamorous infrastructure that keeps event-driven systems debuggable",
      ],
    },
    {
      id: "tbe-production-caching",
      sectionId: "founding-backend",
      title: "Production caching with Redis",
      description:
        "Cache-aside vs write-through, Redis data-structure patterns beyond key-value, stampede prevention.",
      cards: [],
      prerequisites: [],
      concepts: [
        "Cache-aside is the default — app writes DB, invalidates cache; simpler than write-through",
        "Redis sorted sets for leaderboards and sliding windows; streams for log-like consumption",
        "Cache stampede: add jittered TTL + probabilistic early refresh, or use locks (SETNX with expiry)",
        "TTL-based invalidation beats event-based invalidation for 90% of cases — simpler is correctness",
        "Redis cluster mode changes semantics (multi-key ops require same slot); know before you need it",
      ],
    },
    {
      id: "tbe-distributed-tracing-in-practice",
      sectionId: "founding-backend",
      title: "Distributed tracing with OpenTelemetry in Rust",
      description:
        "Theory is in the vault; this lesson is SDK wiring. OTLP exporter, span propagation across async and HTTP boundaries, sampling at scale.",
      cards: [],
      prerequisites: ["tbe-axum-handlers-and-state"],
      concepts: [
        "tracing crate + tracing-opentelemetry bridge emits OTLP-compatible spans",
        "Propagate context across HTTP via W3C traceparent header — requests without it start new traces",
        "Async boundaries break parent-child span relationships unless you use .instrument() correctly",
        "Head sampling (decide at trace start) vs tail sampling (decide after complete trace) — tail catches errors, costs more",
        "Span cardinality is a silent cost driver; bounded attribute sets beat user-controlled strings",
      ],
    },

    // ----- Domain 3: Kubernetes for Backend Engineers -----
    {
      id: "tbe-k8s-workloads",
      sectionId: "founding-backend",
      title: "Kubernetes workload primitives",
      description:
        "Pod, Deployment, Service, Ingress, StatefulSet — the backend-eng-relevant K8s surface without platform-eng depth.",
      cards: [],
      prerequisites: [],
      concepts: [
        "Pod is the unit of scheduling; rarely used directly — Deployment manages ReplicaSets which manage Pods",
        "StatefulSet preserves pod identity and stable storage — use when pods need to differ (leaders, shards)",
        "Service is a stable virtual IP routing to pod endpoints; ClusterIP for internal, LoadBalancer for external",
        "Ingress is the HTTP/S L7 entry point — needs an ingress controller (nginx, traefik, cloud-native)",
        "Liveness, readiness, startup probes do different things — liveness restarts, readiness removes from service, startup delays the other two",
      ],
    },
    {
      id: "tbe-k8s-scaling-and-reliability",
      sectionId: "founding-backend",
      title: "HPA, PDB, and rolling update discipline",
      description:
        "The three primitives that make K8s production-safe: autoscaling, disruption budgets, update strategy.",
      cards: [],
      prerequisites: ["tbe-k8s-workloads"],
      concepts: [
        "HPA scales replicas on CPU/memory by default; custom metrics (request rate, queue depth) are more useful",
        "Pod Disruption Budget (PDB) sets maxUnavailable or minAvailable for voluntary disruptions (node drains, upgrades)",
        "Only create PDBs when you have 2+ replicas; misaligned minAvailable can prevent HPA scale-down",
        "Rolling updates: maxSurge adds pods before removing old; maxUnavailable allows old pods to die — tune for tolerance",
        "Combine HPA + PDB + graceful shutdown for zero-downtime deploys; any one missing and you drop requests",
      ],
    },
    {
      id: "tbe-k8s-secrets-and-config",
      sectionId: "founding-backend",
      title: "Config, secrets, and identity in Kubernetes",
      description:
        "ConfigMap, Secret, and the external secrets pattern. Service accounts and cloud workload identity.",
      cards: [],
      prerequisites: ["tbe-k8s-workloads"],
      concepts: [
        "ConfigMap is for non-sensitive config; Secret is base64, not encryption — never treat Secret as sufficient",
        "External secrets operators (SOPS, sealed-secrets, External Secrets Operator) fetch from a real secret store",
        "ServiceAccount maps to IAM in cloud (IRSA on AWS, Workload Identity on GCP) — avoids long-lived cloud creds in pods",
        "Mounted secrets update automatically (~60s lag); env-var secrets require pod restart to update",
        "Namespaces are the isolation boundary for RBAC; plan them before prod — retrofitting is painful",
      ],
    },

    // ----- Domain 4: Terraform on AWS/GCP -----
    {
      id: "tbe-terraform-modules-and-versioning",
      sectionId: "founding-backend",
      title: "Terraform modules and semantic versioning",
      description:
        "The modules-as-packages discipline that separates weekend Terraform from production Terraform.",
      cards: [],
      prerequisites: [],
      concepts: [
        "Standard module structure: main.tf, variables.tf, outputs.tf, versions.tf — consistency beats cleverness",
        "Modules in separate repos with semver tags (v1.2.3); consuming code pins to tagged versions, not main",
        "Maintain CHANGELOG.md; breaking changes bump MAJOR",
        "Registry (Terraform Cloud, private) or git tags are both fine; pick one and stick",
        "Nested modules are an antipattern past 2 levels — flatten or split",
      ],
    },
    {
      id: "tbe-terraform-state-backends",
      sectionId: "founding-backend",
      title: "Terraform state backends and environment separation",
      description:
        "State is the live prod-coupling artifact; treat accordingly.",
      cards: [],
      prerequisites: ["tbe-terraform-modules-and-versioning"],
      concepts: [
        "AWS: S3 backend + DynamoDB lock table prevents concurrent apply state corruption",
        "GCP: GCS backend with object locking — same pattern, cloud-native primitives",
        "Read access to state file = read access to prod (DB passwords, IP addresses); audit accordingly",
        "Environment separation via directories (environments/dev, staging, prod) with own state — explicit and auditable",
        "Workspaces exist but share a backend and state; directories are the 2026 default",
      ],
    },
    {
      id: "tbe-terraform-secrets-and-drift",
      sectionId: "founding-backend",
      title: "Secrets handling and drift detection in Terraform",
      description:
        "Where Terraform plays with secrets managers, and why drift is the ambient failure mode.",
      cards: [],
      prerequisites: ["tbe-terraform-state-backends"],
      concepts: [
        "Never output secrets — write them to Secrets Manager/Secret Manager during apply; apps fetch at runtime",
        "terraform plan in PR is the review surface; apply only after merge + plan re-run",
        "Drift detection (terraform plan in cron) catches manual console changes; integrate with alerting",
        "Drift remediation is a decision: import, apply-to-match, or delete-and-recreate",
        "Console access should be read-only in prod after bootstrap — drift prevention > drift remediation",
      ],
    },

    // ----- Domain 5: Founding/Staff Engineer Practice -----
    {
      id: "tbe-staff-scope-shift",
      sectionId: "founding-backend",
      title: "The staff-engineer scope shift",
      description:
        "From 'measured by code' to 'measured by impact radius.' Most senior-IC patterns break at staff; practice the replacements before you need them.",
      cards: [],
      prerequisites: [],
      concepts: [
        "Senior engineer: owns features end-to-end. Staff engineer: sets context so other engineers own features well",
        "RFC/design-doc authorship is the medium of leverage — write the first RFC that sets the team's pattern",
        "Influence without management authority means consensus-building beats decree; technical conviction + social capital",
        "The cost of context-switching to mentor scales with team size; schedule 'office hours' rather than async DMs",
        "Visibility matters: your work is cross-cutting and invisible by default; weekly digest to stakeholders is not vanity",
      ],
    },
    {
      id: "tbe-zero-to-one-infra-tradeoffs",
      sectionId: "founding-backend",
      title: "Zero-to-one infrastructure tradeoffs",
      description:
        "What v0 can skip without regret, what becomes a one-way door. Founding engineers get wrong calls wrong for years.",
      cards: [],
      prerequisites: ["tbe-staff-scope-shift"],
      concepts: [
        "Skippable at v0: full IaC, blue-green deploys, service mesh, GraphQL, feature flags (use env flags)",
        "Not skippable: backups with tested restore, auth boundary with tenant isolation, observability baseline",
        "One-way doors: user ID scheme, primary data model, tenant isolation strategy, auth provider choice",
        "Two-way doors: language within stack, queue implementation, caching layer, frontend framework",
        "'Boring tech until it hurts' is survivorship-biased; for founding eng it's load-bearing — novel tech = hiring friction",
      ],
    },
    {
      id: "tbe-technical-direction-in-uncertainty",
      sectionId: "founding-backend",
      title: "Setting technical direction under uncertainty",
      description:
        "Calibration, standards-before-deviations, and the early-stage 'two one-way doors' framing.",
      cards: [],
      prerequisites: ["tbe-staff-scope-shift"],
      concepts: [
        "Set lint/format/test/CI standards on day one — retrofitting is a cultural battle, day-one is a norm",
        "Decision log (ADR discipline) — future hires reread them; hand-waving from memory is technical debt",
        "Two one-way doors framing: name the door, name what closes it, name the cost of being wrong",
        "Don't prematurely optimize team structure; do prematurely optimize decision visibility",
        "'Yes we thought about that' is only credible when there's a written doc — verbal vetoes don't scale",
      ],
    },

    // ----- Domain 6: AI/ML Backend Integration -----
    {
      id: "tbe-llm-serving-backend",
      sectionId: "founding-backend",
      title: "LLM serving infrastructure",
      description:
        "vLLM, continuous batching, quantization tradeoffs, streaming. The backend surface of LLM-powered products.",
      cards: [],
      prerequisites: [],
      concepts: [
        "vLLM + PagedAttention (per 2024 paper) trades 20-26% kernel overhead for KV-cache efficiency at scale",
        "Continuous batching beats static batching by 2-10× for interactive serving",
        "NF4 vs FP8 quantization tradeoffs differ on reasoning-heavy evals; quantization is not free on hard domains",
        "SSE streaming for token-by-token output is the browser-default; WebSocket adds bidirectionality if needed",
        "Context compaction (summarization past a threshold) is the difference between usable and unusable long sessions",
      ],
    },
    {
      id: "tbe-agent-product-infra",
      sectionId: "founding-backend",
      title: "Agent product infrastructure",
      description:
        "What a coding-agent or dev-tooling product actually needs server-side — directly relevant to Tailcall's product surface.",
      cards: [],
      prerequisites: ["tbe-llm-serving-backend"],
      concepts: [
        "Tool orchestration is the real engineering: permission model, timeout handling, output truncation, cost tracking",
        "Session state persistence — memory of prior turns, cache of tool results, invalidation on code edits",
        "Context compaction: summarize old turns past a threshold; this is where Claude Code spends 46k LOC of QueryEngine",
        "Rate limiting per user + per workspace + per organization; usage-based billing rides on the same signals",
        "Observability for agents: trace tool calls as spans, cost per session, abandonment vs completion — metric design is the product",
      ],
    },
  ],
};

// === Practice bridges (cross-domain, separate from lessons) ===
//
// These are implementation exercises that tie lessons to job-relevant work.
// They are not cards; they are checkpoints for the "prove it by shipping"
// track that the red team identified as the load-bearing hiring signal.
//
// 1. Minimal axum + sqlx + Postgres CRUD service, Dockerized (D1)
// 2. Add OpenTelemetry tracing across a 3-hop service (D1 + D2)
// 3. Terraform deploying the service to EKS/GKE with state backend + IAM (D3 + D4)
// 4. HPA + PDB set; chaos-test by draining a node (D3)
// 5. Real RFC for a Tailcall-shaped feature ("persistent agent memory") (D5)
// 6. Contribute a non-trivial PR to an axum or tokio OSS crate (D1, signal)
// 7. Minimal LLM-backed tool-calling agent in Rust (D1 + D6)
// 8. Deploy full stack, write a post-mortem on a real incident or near-miss (D5)

// === Subset for flashcards only (concept-retention track) ===
//
// If wiring into the app, the full FOUNDING_BACKEND_SECTION is fine — all
// 18 lessons are legitimately concept-testable. Unlike dl-compiler-path.ts,
// there is no subset recommended here because backend/infra vocabulary
// benefits from spaced repetition in ways that DL-compiler internals
// (which need implementation practice) do not.
